<a href="https://colab.research.google.com/github/rafaelmartinsdesouza/decisoesdenegociosbaseadasemdadosi.io/blob/PythonparaDataScience/04_Aula_01_17_10_2026_Estrutura_de_Dados_ParteIII.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# FGV EPGE - Escola de Pós-Graduação em Economia
---
## Mestrado Profissional em Economia
### Python para Análise de Dados/Decisões de Negócios Baseadas em Dados I - 2026-4
---
#### Professor: Rafael Martins de Souza (rafael.souza@fgv.br)

##### Doutor em Economia (EPGE, 2009), Mestre (UFRJ, 2003) e Bacharel em Estatística (ENCE, 2000).
---
##### Monitora: Lívia Meinhardt, FGV EMAp

##### Doutoranda em Matemática, Mestre Modelagem Matemática (2025) e Ciência de Dados e Bacharel em Ciência de Dados e Inteligência Artificial (2023), FGV EMAp.

# Aula 1 - Parte IV


- Principais Estruturas de Dados (Parte 3)
- Condicionais
- Loop

## Estruturas de Dados

- <font color='green'>Tipos numéricos (visto)</font>
- <font color = 'green'>Lista (visto)</font>
- <font color = 'green'>String (visto)</font>
- <font color = 'green'>Conjuntos (visto)</font>
- Dicionários
- Tuplas

### Tipo Dicionário:
Dicionários são sequências de itens na forma de pares *key:values* que se encontram dentro de chaves e separados por vírgula.

Comandos interessantes: get, items, keys, update, values

**Observações:**

**1) Keys são únicas, values podem ser repetidos**

**2) Tipos mutáveis não podem ser chaves em dicionários. Valores podem ser mutáveis**

In [ ]:
dicionario = {'chave1':[1,2,3],'chave2':2,'outra chave':4, 45: 26, 'outro':23}
dicionario

{'chave1': [1, 2, 3], 'chave2': 2, 'outra chave': 4, 45: 26, 'outro': 23}

Checando as chaves

In [ ]:
dicionario.keys()

dict_keys(['chave1', 'chave2', 'outra chave', 45, 'outro'])

Checando os valores

In [ ]:
dicionario.values()

dict_values([[1, 2, 3], 2, 4, 26, 23])

In [ ]:
dicionario2 = {'chave2': 2, 'chave1':[1,2,3],'outra chave':4, 45: 26, 'outro':23}
dicionario2

{'chave2': 2, 'chave1': [1, 2, 3], 'outra chave': 4, 45: 26, 'outro': 23}

In [ ]:
print(dicionario2['chave1'])
print(type(dicionario2['chave1']))
print(dicionario2['chave1'][0])
print(dicionario2['chave1'][1])
dicionario2['chave1'][2]
print(dicionario2['chave1'])
print(dicionario2['chave1'][0], dicionario2['chave1'][1], dicionario2['chave1'][2])

Exemplo 1

In [ ]:
ficha = {'Peso': 73, 'Altura': 183, 'Idade':44, 'Nome':'Renato'}
ficha

{'Peso': 73, 'Altura': 183, 'Idade': 44, 'Nome': 'Renato'}

Acessando as chaves de 2 formas. Via '[]' ou via o método 'get'. A principal diferença é que caso a chave não exista, é possível definir no get um valor 'default'. Acessando via colchetes daria erro.

In [ ]:
ficha['Idade']

44

Vai dar <font color='red'>erro</font>

In [ ]:
ficha['Profissão']

KeyError: 'Profissão'

In [ ]:
ficha.get('Profissão', 'Não existe essa chave')

'Não existe essa chave'

Adicionar uma chave. Basta usar o update com outro dicionário

In [ ]:
ficha.update({'Profissão':'Professor'})

In [ ]:
ficha.keys()

dict_keys(['Peso', 'Altura', 'Idade', 'Nome', 'Profissão'])

O método 'items' transforma o par 'key:value' em tuplas

In [ ]:
ficha.items()

### Tipo Tupla:
Tuplas, assim como listas, são sequências ordenadas de itens. As diferenças entre elas são: os elementos estão entre parênteses e as tuplas são imutáveis, **seus elementos não podem ser modificados**.

In [ ]:
t = (1,2,3,4,7,4,3,1,'string',{1,2}, [1,2])
t = 1,2,3,4,7,4,3,1,'string',{1,2}, [1,2]

In [ ]:
type(t)

tuple

In [ ]:
type(t[-1])

list

In [ ]:
type(t[-2])

set

In [ ]:
conjunto = {1, 2,2,2,3}

In [ ]:
conjunto

{1, 2, 3}

Acessando cada elemento da tupla

In [ ]:
t[0]

1

In [ ]:
l = [1,2,3,4,7,4,3,1,'string',{1,2}, [1,2]]

In [ ]:
t[0] = 2

TypeError: 'tuple' object does not support item assignment

In [ ]:
l[0] = 2

In [ ]:
l

[2, 2, 3, 4, 7, 4, 3, 1, 'string', {1, 2}, [1, 2]]

In [ ]:
t[5]

4

In [ ]:
t[-1][0] = 2

In [ ]:
t

(1, 2, 3, 4, 7, 4, 3, 1, 'string', {1, 2}, [2, 2])

In [ ]:
tuplathais = (1,(1,2,3), 2)

In [ ]:
tuplathais

(1, (1, 2, 3), 2)

In [ ]:
tuplathais[1][0]

1

In [ ]:
t[3:6]

(4, 7, 4)

In [ ]:
lista = [1,2,3]

In [ ]:
tupla = tuple(lista)

In [ ]:
tupla

(1, 2, 3)

In [ ]:
lista2 = list(tupla)

In [ ]:
lista2

[1, 2, 3]

In [ ]:
tupla[-2]

2

In [ ]:
d5 = {(1,2): 'tupla'}
print(type(d5))
c5 = {(1,2), 'tupla'}
print(type(c5))

<class 'dict'>
<class 'set'>

In [ ]:
t2 = (2,4,7,2,2,2,2, 2)
print(t2)

(2, 4, 7, 2, 2, 2, 2, 2)

In [ ]:
t2.count(2)

6

In [ ]:
print(t2[0])
#t2[0] = 1
l2 = [2,4,7,2,2,2,2, 2]
print(l2[0])
l2[0] = 1
print(l2)

2
2
[1, 4, 7, 2, 2, 2, 2, 2]

In [ ]:
x, y = 10, 19 #Relembrando como declarar as variáveis em uma linha
print(y)
print(x)
print(type(x))
print(type((10,19)))
print(type([10,19]))

19
10
<class 'int'>
<class 'tuple'>
<class 'list'>

Empacotamento e desempacotamento de tuplas

In [ ]:
x = 10,19 #Posso declarar uma tupla sem usar os parêntes
z = (10,19) #O mesmo resultado é obtida usando parêntes
print(y)
print(x)
print(type(x))
print(type(z))

19
(10, 19)
<class 'tuple'>
<class 'tuple'>

In [ ]:
t = 2,3,4
x,y,z = t
print(t)
print(x)
print(y)
print(z)

(2, 3, 4)
2
3
4

In [ ]:
# Troca de valores
print('x =',  x)
print('y =', y)
x,y = y,x
print('x =', x)
print('y =', y)

x = 2
y = 3
x = 3
y = 2

Embora tuplas sejam imutáveis, se um elemento da tupla é mutável, é possível modificá-lo

In [ ]:
a = 1,2,[10,20,30]
print(a)
id(a)

(1, 2, [10, 20, 30])

138631561490176

In [ ]:
a[2].append(40)
a[2]

[10, 20, 30, 40]

In [ ]:
print(a)
id(a)

(1, 2, [10, 20, 30, 40])

138631561490176

- Você pode concatenar tuplas usando o operador + para produzir tuplas mais longas
- Multiplicar uma tupla por um inteiro, assim como com listas, gera o efeito de concatenar o mesmo número de cópias

In [ ]:
a

(1, 2, [10, 20, 30, 40])

In [ ]:
a*3
print(a*3)
b = a*2
b = b*2
print(b)

(1, 2, [10, 20, 30, 40], 1, 2, [10, 20, 30, 40], 1, 2, [10, 20, 30, 40])
(1, 2, [10, 20, 30, 40], 1, 2, [10, 20, 30, 40], 1, 2, [10, 20, 30, 40], 1, 2, [10, 20, 30, 40])

### Só há dois métodos para tuplas: count e index - Conteúdo complementar

- Count: frequência absoluta de um dado objeto
- Index: índice da primeira aparição de um objeto

In [ ]:
t2

(2, 4, 7, 2, 2, 2, 2, 2)

In [ ]:
t2.count(2)

6

In [ ]:
t2.index(2)

0

**Exemplo 2: Tuplas + Dicionários**

A partir de um código que exporta um relatório do FMI, criou-se um dicionário com as previsões de PIB para vários países.

In [ ]:
import urllib.request
import pandas as pd

## fazendo o download

urllib.request.urlretrieve('https://www.imf.org/~/media/Files/Publications/WEO/2020/Update/June/English/data/WEOJun2020update.ashx?la=en', "WEOJun2020update.xlsx")

('WEOJun2020update.xlsx', <http.client.HTTPMessage at 0x79054d657050>)

In [ ]:
df = pd.read_excel('WEOJun2020update.xlsx', sheet_name='Real GDP Growth', header = 6)
## Forma alternativa usando a posição da tabela
#df = pd.read_excel('WEOJun2020update.xlsx', sheet_name=2, header = 6)
print(df.head())
print(df.tail())

  Unnamed: 0  2018  2019  2020  2021  Unnamed: 5  2020.1  2021.1
0        NaN   NaN   NaN   NaN   NaN         NaN     NaN     NaN
1  Argentina  -2.5  -2.2  -9.9   3.9         NaN    -4.2    -0.5
2  Australia   2.8   1.8  -4.5   4.0         NaN     2.2    -2.1
3     Brazil   1.3   1.1  -9.1   3.6         NaN    -3.8     0.7
4     Canada   2.0   1.7  -8.4   4.9         NaN    -2.2     0.7
                                           Unnamed: 0  2018  2019  2020  2021  \
28                                             Turkey   2.8   0.9  -5.0   5.0
29                                     United Kingdom   1.3   1.4 -10.2   6.3
30                                      United States   2.9   2.3  -8.0   4.5
31                                                NaN   NaN   NaN   NaN   NaN
32  Source: International Monetary Fund, World Eco...   NaN   NaN   NaN   NaN

    Unnamed: 5  2020.1  2021.1
28         NaN     0.0     0.0
29         NaN    -3.7     2.3
30         NaN    -2.1    -0.2
31         NaN     NaN     NaN
32         NaN     NaN     NaN

In [ ]:
## lendo o arquivo

df = pd.read_excel('WEOJun2020update.xlsx', sheet_name=2, header = 6)

## Renomeando uma coluna

df.rename(columns = {'Unnamed: 0':'Country'}, inplace = True)

## Deletando 3 linhas (a primeira, a última e a penúltima) - Inspecionei usando df.head() e df.tail()

df.drop(df.index[[0,-1,-2]], inplace = True)

## Deletando algumas colunas sem nome

cols_unnamed = [cols_del for cols_del in df.columns if 'Unnamed' in str(cols_del)]
cols_unnamed = cols_unnamed + ['2020.1','2021.1']
print(cols_unnamed)
df.drop(cols_unnamed, axis = 1, inplace = True)

## Definindo a coluna 'Country' como index

df.set_index('Country', inplace = True)

['Unnamed: 5', '2020.1', '2021.1']

In [ ]:
print(df.head())
print(df.tail())

           2018  2019  2020  2021
Country
Argentina  -2.5  -2.2  -9.9   3.9
Australia   2.8   1.8  -4.5   4.0
Brazil      1.3   1.1  -9.1   3.6
Canada      2.0   1.7  -8.4   4.9
China       6.7   6.1   1.0   8.2
                2018  2019  2020  2021
Country
Spain            2.4   2.0 -12.8   6.3
Thailand         4.2   2.4  -7.7   5.0
Turkey           2.8   0.9  -5.0   5.0
United Kingdom   1.3   1.4 -10.2   6.3
United States    2.9   2.3  -8.0   4.5

In [ ]:
df[0: 5]
#df['Argentina']
#df.index['Argentina']
#df.drop(df.index['Argentina'], inplace = True)

           2018  2019  2020  2021
Country
Argentina  -2.5  -2.2  -9.9   3.9
Australia   2.8   1.8  -4.5   4.0
Brazil      1.3   1.1  -9.1   3.6
Canada      2.0   1.7  -8.4   4.9
China       6.7   6.1   1.0   8.2

In [ ]:
df.head()

           2018  2019  2020  2021
Country
Argentina  -2.5  -2.2  -9.9   3.9
Australia   2.8   1.8  -4.5   4.0
Brazil      1.3   1.1  -9.1   3.6
Canada      2.0   1.7  -8.4   4.9
China       6.7   6.1   1.0   8.2

In [ ]:
df.head()
#data_isadora = df.drop("Argentina")
#data_isadora.head()
#data = df.drop("2021")
#data.head()

           2018  2019  2020  2021
Country
Argentina  -2.5  -2.2  -9.9   3.9
Australia   2.8   1.8  -4.5   4.0
Brazil      1.3   1.1  -9.1   3.6
Canada      2.0   1.7  -8.4   4.9
China       6.7   6.1   1.0   8.2

In [ ]:
#dict_gdp = df.to_dict()

In [ ]:
dict_gdp_2020 = {'Argentina': -9.9,
 'Australia': -4.5,
 'Brazil': -9.1,
 'Canada': -8.4,
 'China': 1.0,
 'Egypt 2/': 2.0,
 'France': -12.5,
 'Germany': -7.8,
 'India 2/': -4.5,
 'Indonesia': -0.3,
 'Iran 2/': -6.0,
 'Italy': -12.8,
 'Japan': -5.8,
 'Kazakhstan': -2.7,
 'Korea': -2.1,
 'Malaysia': -3.8,
 'Mexico': -10.5,
 'Netherlands': -7.7,
 'Nigeria': -5.4,
 'Pakistan 2/': -0.4,
 'Philippines': -3.6,
 'Poland': -4.6,
 'Russia': -6.6,
 'Saudi Arabia': -6.8,
 'South Africa': -8.0,
 'Spain': -12.8,
 'Thailand': -7.7,
 'Turkey': -5.0,
 'United Kingdom': -10.2,
 'United States': -8.0}

In [ ]:
dict_gdp_2020

{'Argentina': -9.9,
 'Australia': -4.5,
 'Brazil': -9.1,
 'Canada': -8.4,
 'China': 1.0,
 'Egypt 2/': 2.0,
 'France': -12.5,
 'Germany': -7.8,
 'India 2/': -4.5,
 'Indonesia': -0.3,
 'Iran 2/': -6.0,
 'Italy': -12.8,
 'Japan': -5.8,
 'Kazakhstan': -2.7,
 'Korea': -2.1,
 'Malaysia': -3.8,
 'Mexico': -10.5,
 'Netherlands': -7.7,
 'Nigeria': -5.4,
 'Pakistan 2/': -0.4,
 'Philippines': -3.6,
 'Poland': -4.6,
 'Russia': -6.6,
 'Saudi Arabia': -6.8,
 'South Africa': -8.0,
 'Spain': -12.8,
 'Thailand': -7.7,
 'Turkey': -5.0,
 'United Kingdom': -10.2,
 'United States': -8.0}

Usando a função nativa 'sorted' para ordenar o dicionário pelos valores.

O método *Items* transforma o dicionário em tuplas e a função anônima *lambda* acessa o segundo item da tupla, ou seja, a previsão de crescimento do PIB.

In [ ]:
dict_gdp_2020.items()

dict_items([('Argentina', -9.9), ('Australia', -4.5), ('Brazil', -9.1), ('Canada', -8.4), ('China', 1.0), ('Egypt 2/', 2.0), ('France', -12.5), ('Germany', -7.8), ('India 2/', -4.5), ('Indonesia', -0.3), ('Iran 2/', -6.0), ('Italy', -12.8), ('Japan', -5.8), ('Kazakhstan', -2.7), ('Korea', -2.1), ('Malaysia', -3.8), ('Mexico', -10.5), ('Netherlands', -7.7), ('Nigeria', -5.4), ('Pakistan 2/', -0.4), ('Philippines', -3.6), ('Poland', -4.6), ('Russia', -6.6), ('Saudi Arabia', -6.8), ('South Africa', -8.0), ('Spain', -12.8), ('Thailand', -7.7), ('Turkey', -5.0), ('United Kingdom', -10.2), ('United States', -8.0)])

In [ ]:
dict_gdp_2020

{'Argentina': -9.9,
 'Australia': -4.5,
 'Brazil': -9.1,
 'Canada': -8.4,
 'China': 1.0,
 'Egypt 2/': 2.0,
 'France': -12.5,
 'Germany': -7.8,
 'India 2/': -4.5,
 'Indonesia': -0.3,
 'Iran 2/': -6.0,
 'Italy': -12.8,
 'Japan': -5.8,
 'Kazakhstan': -2.7,
 'Korea': -2.1,
 'Malaysia': -3.8,
 'Mexico': -10.5,
 'Netherlands': -7.7,
 'Nigeria': -5.4,
 'Pakistan 2/': -0.4,
 'Philippines': -3.6,
 'Poland': -4.6,
 'Russia': -6.6,
 'Saudi Arabia': -6.8,
 'South Africa': -8.0,
 'Spain': -12.8,
 'Thailand': -7.7,
 'Turkey': -5.0,
 'United Kingdom': -10.2,
 'United States': -8.0}

In [ ]:
dir()

['In',
 'Out',
 '_',
 '_1',
 '_10',
 '_11',
 '_12',
 '_6',
 '_7',
 '_8',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i11',
 '_i12',
 '_i13',
 '_i2',
 '_i3',
 '_i4',
 '_i5',
 '_i6',
 '_i7',
 '_i8',
 '_i9',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'cols_unnamed',
 'df',
 'dict_gdp_2020',
 'exit',
 'get_ipython',
 'pd',
 'quit',
 'urllib']

In [ ]:
sorted(dict_gdp_2020.items(), key = lambda x:x[1])

[('Italy', -12.8),
 ('Spain', -12.8),
 ('France', -12.5),
 ('Mexico', -10.5),
 ('United Kingdom', -10.2),
 ('Argentina', -9.9),
 ('Brazil', -9.1),
 ('Canada', -8.4),
 ('South Africa', -8.0),
 ('United States', -8.0),
 ('Germany', -7.8),
 ('Netherlands', -7.7),
 ('Thailand', -7.7),
 ('Saudi Arabia', -6.8),
 ('Russia', -6.6),
 ('Iran 2/', -6.0),
 ('Japan', -5.8),
 ('Nigeria', -5.4),
 ('Turkey', -5.0),
 ('Poland', -4.6),
 ('Australia', -4.5),
 ('India 2/', -4.5),
 ('Malaysia', -3.8),
 ('Philippines', -3.6),
 ('Kazakhstan', -2.7),
 ('Korea', -2.1),
 ('Pakistan 2/', -0.4),
 ('Indonesia', -0.3),
 ('China', 1.0),
 ('Egypt 2/', 2.0)]

In [ ]:
sorted(dict_gdp_2020.items(), key = lambda x:x[1], reverse = True)

[('Egypt 2/', 2.0),
 ('China', 1.0),
 ('Indonesia', -0.3),
 ('Pakistan 2/', -0.4),
 ('Korea', -2.1),
 ('Kazakhstan', -2.7),
 ('Philippines', -3.6),
 ('Malaysia', -3.8),
 ('Australia', -4.5),
 ('India 2/', -4.5),
 ('Poland', -4.6),
 ('Turkey', -5.0),
 ('Nigeria', -5.4),
 ('Japan', -5.8),
 ('Iran 2/', -6.0),
 ('Russia', -6.6),
 ('Saudi Arabia', -6.8),
 ('Netherlands', -7.7),
 ('Thailand', -7.7),
 ('Germany', -7.8),
 ('South Africa', -8.0),
 ('United States', -8.0),
 ('Canada', -8.4),
 ('Brazil', -9.1),
 ('Argentina', -9.9),
 ('United Kingdom', -10.2),
 ('Mexico', -10.5),
 ('France', -12.5),
 ('Italy', -12.8),
 ('Spain', -12.8)]

## Iteráveis

Listas, dicionários, conjuntos e tuplas são objetos **iteráveis (iterable)**. Um iterável é qualquer objeto que é capaz de retornar seus elementos um a um, permitindo uma iteração via *for-loop*

Desempacotando iteráveis

In [ ]:
lista_exemplo = [1,2]

Forma curta

In [ ]:
x,y = lista_exemplo

In [ ]:
x

1

In [ ]:
y

2

In [ ]:
x1 = lista_exemplo[0]
y1 = lista_exemplo[1]

In [ ]:
x1 == x

True

In [ ]:
y1 == y

True

In [ ]:
z,w = {10,20}

In [ ]:
w

20

In [ ]:
z

10

In [ ]:
a,b = {'a':1,'b':2}

In [ ]:
a

'a'

In [ ]:
b

'b'

Curiosidade

In [ ]:
x, *y, w, u = [1,2,3,4,5,6]

In [ ]:
x

1

In [ ]:
y

[2, 3, 4]

In [ ]:
w

5

In [ ]:
u

6

## Exercícios - Monitoria - Conteúdo complementar

### Exercícios 1 - Listas

In [ ]:
lista_para_casa = [75, 56, 15, 1, 37, 19, 41, 66, 74, 64, 2, 66, 20, 13, 9, 40,17, 22, 92, 57]

a) Insira o número 54 elemento da posição 4

b) A média da lista até agora é um elemento da lista? Se, sim indique qual a posição.

c) Adicione à lista até agora uma outra lista: [1,5,10]

d) Adicione à lista até agora apenas os elementos da lista do item **c)**.

e) Exclua o primeiro e o último elemento da lista até agora.

f) O primeiro elemento da lista até agora é par? Use o operador apropriado

g) Inverta a ordem da lista

### Exercício 2 - Dicionários

In [ ]:
dict_gdp_2020.keys()

a) No dicionário 'dict_gdp_2020', adicione as previsões de PIB para 3 países (quaisquer 3). Os valores podem ser fictícios. O importante é usar o comando certo.

b) Remova a previsão para 'Argentina'. Use o comando correto e diferencie o método 'pop' e 'popitem'.